#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyjTR/RmqsJGoEgZ+7j7ZyaN4ux2oqqdRXWbonicQnNQm2Vvr4cZ81+sDnFkGVUvda5vnjaUQCDmShZxGbRn/1VzIlds9hyCts505E8a5spy3ys5sy2Ly08rjVBJ4y9oZmQuthO6Tu1bYh191VedPrdX4qGlGFNqmkksPRDr90aLFKocU9t+hWh1RzqKsd79mZoqr6AzQAksSdxyIu9kxhKaigAtn7NAwMP73KGuKrqvtwaQIsiVPDuhy78qm7zWEijBpMlYKCy+tc6yb/d7GI5c6zo9/DxD3ECOhK3kN6LoNKXyGqOzwOibib/UxbG9+E1+X2R0YfzicYhMlfI+uV guolin@guolindeMBP
